version: "3"

services:

  db:
    image: postgres:11
    environment:
      POSTGRES_PASSWORD: sonar
      POSTGRES_USER: sonar
      POSTGRES_DB: sonar
    volumes:
      - ${HOME}/.sonar/db:/var/lib/postgresql/data

  sonar:
    image: sonarqube:7.9-community
    depends_on:
      - db
    ports:
      - "9000:9000"
    environment:
      sonar.jdbc.username: sonar
      sonar.jdbc.password: sonar
      sonar.jdbc.url: jdbc:postgresql://db/sonar
